### ISSUE TITLE
Got a few errors when I tried to run the Application...

### ISSUE THREAD

**Issue by gosh123** [aranyia/WhoIsThis#2]
The following imports are shown as errors....
import com.facebook.android.*;
import com.facebook.android.Facebook.DialogListener;

can you please clear this issue...Is there any workaround?

**Comment by aranyia** [comment]
Hi,

Probably I should have mentioned as a documentation that it depends on the Facebook SDK project for Android. You can refer to the 'Setup for Eclipse' section of this page on how to include the SDK as a dependency: https://developers.facebook.com/docs/android/getting-started/
That being said this project was last compiled in 2011, so there is a chance that because of the newer Facebook SDK versions the app's implementation has to be changed for compatibility.
I suggest to create your own Facebook app at the Facebook development console. In theory if you change the FB_APP_ID in the FacebookFeed class to your own, it should work. You must also generate a hash key for your app build on your machine, you can refer to the 'Create a Development Key Hash' section at the link above.
But I also must point out that the "me/friends" request won't give you the complete list of a user's friends anymore because of the recent changes made in the Facebook API. Instead it will only show those friends who are also using your Facebook app. Either way you can test it with Facebook test users which can be created in the Facebook development console.

**Comment by gosh123** [comment]
Do you remember the version of SDK https://developers.facebook.com/docs/android/downloads/

**Comment by aranyia** [comment]
It was prior to 3.0. Probably it should work with the earliest 3.0 version if the key classes and methods were only deprecated but not removed. Some documentation is available on how to upgrade from 2.x to 3.0 if it's needed: https://developers.facebook.com/docs/android/upgrading/#20to30
